### ISSUE TITLE
Transaction panics when comparing public capability to `nil`

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#192]
### Problem

When getting a public capability from an `AuthAccount` and comparing it to `nil`, the execution panics.

### Steps to Reproduce

1. Run this transaction:
```
transaction {
  prepare(acct: AuthAccount) {
    if acct.getCapability(/public/test) == nil {
      log("it works")
    }
  }
}
```
2. See panic:
```
WARN[3754] ❗  Transaction reverted                       txID=fc64e8078cd493038a12372bfb8c2da1aae7b2310cc55a01a75bdb5c400c831d
WARN[3754] ERR [fc64e8] code execution failed: Execution failed:
unreachable
goroutine 206 [running]:
runtime/debug.Stack(0x4dfd0a0, 0x52594c0, 0xc002e203e0)
        runtime/debug/stack.go:24 +0x9d
github.com/onflow/cadence/runtime/errors.NewUnreachableError(...)
        github.com/onflow/cadence@v0.4.0/runtime/errors/errors.go:44
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).testEqual(0xc002cb98c0, 0x5258e60, 0xc002e20400, 0x5259940, 0x6f83920, 0xc00361c378)
        github.com/onflow/cadence@v0.4.0/runtime/interpreter/interpreter.go:1730 +0x160
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitBinaryExpression.func16(0x4dd9180, 0xc002e208c0, 0xc002e20980, 0xc00361c3f8)
        github.com/onflow/cadence@v0.4.0/runtime/interpreter/interpreter.go:1632 +0x67
github.com/onflow/cadence/runtime/trampoline.MapTrampoline.func1(0x4dd9180, 0xc002e208c0, 0xc002e205a0, 0x1339a7240524a740)
        github.com/onflow/cadence@v0.4.0/runtime/trampoline/trampoline.go:50 +0x39
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x4dd9180, 0xc002e208c0, 0xc002e208c0, 0xc002e20960)
        github.com/onflow/cadence@v0.4.0/runtime/trampoline/trampoline.go:123 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x4dd9180, 0xc002e208c0, 0x4cf7fa0, 0xc002e20980)
        github.com/onflow/cadence@v0.4.0/runtime/trampoline/trampoline.go:123 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.Resume.func1(0xc002e20960, 0x4cf7fa0)
        github.com/onflow/cadence@v0.4.0/runtime/trampoline/trampoline.go:134 +0x37
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runUntilNextStatement(0xc002cb98c0, 0x524a740, 0xc002e20960, 0x0, 0x0, 0xc002e20600)
        github.com/onflow/cadence@v0.4.0/runtime/interpreter/interpreter.go:585 +0x35
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runAllStatements(0xc002cb98c0, 0x524a740, 0xc001dfb5a0, 0x1, 0x1)
        github.com/onflow/cadence@v0.4.0/runtime/interpreter/interpreter.go:595 +0x56
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeTransaction(0xc002cb98c0, 0x0, 0xc00070c1f0, 0x1, 0x1, 0x0, 0x0)
        github.com/onflow/cadence@v0.4.0/runtime/interpreter/interpreter.go:813 +0x137
github.com/onflow/cadence/runtime.(*interpreterRuntime).transactionExecutionFunction.func1(0xc002cb98c0, 0x0, 0x0, 0xc00361c710, 0xc00361c710)
        github.com/onflow/cadence@v0.4.0/runtime/runtime.go:390 +0x575
github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret.func1()
        github.com/onflow/cadence@v0.4.0/runtime/runtime.go:191 +0xa4
github.com/onflow/cadence/runtime.reportMetric(0xc00361c838, 0x5269660, 0xc002c1e0d0, 0xc00361c820)
        github.com/onflow/cadence@v0.4.0/runtime/runtime.go:97 +0xf3
github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret(0x6f83920, 0x522db20, 0xc002146820, 0x5269660, 0xc002c1e0d0, 0xc002146840, 0xc0004c4d00, 0xc000138000, 0x7, 0xa, ...)
        github.com/onflow/cadence@v0.4.0/runtime/runtime.go:185 +0x1d2
github.com/onflow/cadence/runtime.(*interpreterRuntime).ExecuteTransaction(0x6f83920, 0xc000020240, 0xb8, 0xc0, 0x6f83920, 0x0, 0x0, 0x5269660, 0xc002c1e0d0, 0x522db20, ...)
        github.com/onflow/cadence@v0.4.0/runtime/runtime.go:298 +0x57c
github.com/dapperlabs/flow-go/engine/execution/computation/virtualmachine.(*virtualMachine).executeTransaction(...)
        github.com/dapperlabs/flow-go@v0.4.1-0.20200602235543-7c086e054cc3/engine/execution/computation/virtualmachine/virtualMachine.go:68
github.com/dapperlabs/flow-go/engine/execution/computation/virtualmachine.(*blockContext).ExecuteTransaction(0xc001b02cc0, 0x52426c0, 0xc003094540, 0xc0001249c0, 0xc002d5e420, 0x2, 0x2, 0xc003094540, 0x0, 0x6f83920)
        github.com/dapperlabs/flow-go@v0.4.1-0.20200602235543-7c086e054cc3/engine/execution/computation/virtualmachine/blockContext.go:135 +0x24d
github.com/dapperlabs/flow-emulator.(*Blockchain).executeNextTransaction.func1(0xc003094540, 0xc0001249c0, 0xc002b94e20, 0xc003402528, 0x795b008)
        github.com/dapperlabs/flow-emulator@v0.4.0/blockchain.go:586 +0xdd
github.com/dapperlabs/flow-emulator.(*pendingBlock).ExecuteNextTransaction(0xc001437560, 0xc002b95160, 0xc002c926a0, 0x8, 0x40164af)
        github.com/dapperlabs/flow-emulator@v0.4.0/pendingBlock.go:154 +0x10f
github.com/dapperlabs/flow-emulator.(*Blockchain).executeNextTransaction(0xc00038f480, 0x5242680, 0xc001b02cc0, 0xc00038f480, 0x5242680, 0xc001b02cc0)
        github.com/dapperlabs/flow-emulator@v0.4.0/blockchain.go:581 +0xaf
github.com/dapperlabs/flow-emulator.(*Blockchain).executeBlock(0xc00038f480, 0x10, 0xc002b952b8, 0x45eca17, 0x0, 0x0)
        github.com/dapperlabs/flow-emulator@v0.4.0/blockchain.go:548 +0x147
github.com/dapperlabs/flow-emulator.(*Blockchain).executeAndCommitBlock(0xc00038f480, 0xaa32d30b27b4b879, 0x8c19289c8b185885, 0x8693cef1332bb26c, 0x1573fbfa6b0a639f, 0xf93487d7f889e2d1, 0x7899273455a81143)
        github.com/dapperlabs/flow-emulator@v0.4.0/blockchain.go:667 +0x43
github.com/dapperlabs/flow-emulator.(*Blockchain).ExecuteAndCommitBlock(0xc00038f480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/dapperlabs/flow-emulator@v0.4.0/blockchain.go:661 +0xa9
github.com/dapperlabs/flow-emulator/server.(*Backend).commitBlock(0xc001bf9a40)
        github.com/dapperlabs/flow-emulator@v0.4.0/server/backend.go:422 +0x4c
github.com/dapperlabs/flow-emulator/server.(*Backend).SendTransaction(0xc001bf9a40, 0x5249a80, 0xc000c95f50, 0xc000c95f80, 0xc001bf9a40, 0x5254f60, 0xc002bf3ec0)
        github.com/dapperlabs/flow-emulator@v0.4.0/server/backend.go:86 +0x8e5
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_SendTransaction_Handler.func1(0x5249a80, 0xc000c95f50, 0x4e64f20, 0xc000c95f80, 0x21, 0xc002800aa0, 0x0, 0xc002c9dae8)
        github.com/onflow/flow/protobuf/go/flow@v0.1.5-0.20200601215056-34a11def1d6b/access/access.pb.go:1800 +0x89
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x5249a80, 0xc000c95f50, 0x4e64f20, 0xc000c95f80, 0xc001b028c0, 0xc001b028e0, 0xc002c46b58, 0x410d828, 0x4e54080, 0xc000c95f50)
        github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xad
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_SendTransaction_Handler(0x4ee72c0, 0xc001bf9a40, 0x5249a80, 0xc000c95f50, 0xc004a4a180, 0xc0003e0360, 0x5249a80, 0xc000c95f50, 0xc002966000, 0x150)
        github.com/onflow/flow/protobuf/go/flow@v0.1.5-0.20200601215056-34a11def1d6b/access/access.pb.go:1802 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003e49c0, 0x525ce80, 0xc0004a8480, 0xc0030d0100, 0xc000ac4270, 0x6f54de0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.29.1/server.go:1082 +0x4fd
google.golang.org/grpc.(*Server).handleStream(0xc0003e49c0, 0x525ce80, 0xc0004a8480, 0xc0030d0100, 0x0)
        google.golang.org/grpc@v1.29.1/server.go:1405 +0xd25
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001b97340, 0xc0003e49c0, 0x525ce80, 0xc0004a8480, 0xc0030d0100)
        google.golang.org/grpc@v1.29.1/server.go:746 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.29.1/server.go:744 +0xa1
```
This does not cause an issue when trying to get the capability from storage

### Acceptance Criteria

No panic

**Comment by turbolent** [comment]
Can you please paste the panic?

**Comment by joshuahannan** [comment]
yes indeed, sorry about missing that. I just updated the report to include the panic @turbolent
