### ISSUE TITLE
Calling log crashes the REPL

### ISSUE THREAD

**Issue by dreamsmasher** [onflow/cadence#2106]
### Problem

Calling `log` in the REPL currently throws a nil dereference error instead of the expected behaviour of printing to stdout. 

OS: macos 12.2.1 (2021 M1 MBP 14")
Version: Flow CLI v0.41.2
Logs:

```
Welcome to Cadence v0.28.0!
Type '.help' for assistance.

1> log("hi")
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1008a285c]

goroutine 1 [running]:
github.com/onflow/cadence/runtime.(*REPL).Accept.func1()
        github.com/onflow/cadence@v0.28.0/runtime/repl.go:148 +0xd4
panic({0x101a6e460, 0x10287b4e0})
        runtime/panic.go:884 +0x204
github.com/onflow/cadence/runtime/interpreter.(*Variable).GetValue(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/variable.go:29
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitIdentifierExpression(0x140000f8fc0, 0x1400059d7d0)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:244 +0x4c
github.com/onflow/cadence/runtime/ast.AcceptExpression[...]({0x101cf15a0?, 0x1400059d7d0}, {0x101cfc5f8, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:221 +0x1e8
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalExpression(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:252
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitInvocationExpression(0x140000f8fc0, 0x14000594d20)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:814 +0xf8
github.com/onflow/cadence/runtime/ast.AcceptExpression[...]({0x101cf16c0?, 0x14000594d20}, {0x101cfc5f8, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:218 +0x21c
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalExpression(...)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_expression.go:252
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitExpressionStatement(0x140006a5970?, 0x100395180?)
        github.com/onflow/cadence@v0.28.0/runtime/interpreter/interpreter_statement.go:564 +0x3c
github.com/onflow/cadence/runtime/ast.AcceptStatement[...]({0x101ced410?, 0x1400056afd0}, {0x101cf7d60, 0x140000f8fc0})
        github.com/onflow/cadence@v0.28.0/runtime/ast/visitor.go:135 +0x3bc
github.com/onflow/cadence/runtime.(*REPL).Accept(0x140004eb650, {0x14000053240, 0xa, 0x10})
        github.com/onflow/cadence@v0.28.0/runtime/repl.go:233 +0x558
github.com/onflow/cadence/runtime/cmd/execute.RunREPL.func3({0x14000053150?, 0x0?})
        github.com/onflow/cadence@v0.28.0/runtime/cmd/execute/repl.go:69 +0x110
github.com/c-bata/go-prompt.(*Prompt).Run(0x14000022fc0)
        github.com/c-bata/go-prompt@v0.2.5/prompt.go:84 +0x628
github.com/onflow/cadence/runtime/cmd/execute.RunREPL()
        github.com/onflow/cadence@v0.28.0/runtime/cmd/execute/repl.go:112 +0x288
github.com/onflow/flow-cli/internal/cadence.glob..func1(0x102898540?, {0x1028ed8c0?, 0x0?, 0x0?})
        github.com/onflow/flow-cli/internal/cadence/cadence.go:35 +0x3c
github.com/spf13/cobra.(*Command).execute(0x102898540, {0x140001b4010, 0x0, 0x0})
        github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x140002cec80)
        github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        github.com/onflow/flow-cli/cmd/flow/main.go:84 +0x4a0
```

### Steps to Reproduce

1. open a terminal
2. type 'f'
3. type 'l'
4. type 'o'
5. type 'w'
6. type ' '
7. type 'c'
8. type 'a'
9. type 'd'
10. type 'e'
11. type 'n'
12. type 'c'
13. type 'e'
14. type Enter. now you're in the cadence REPL.
15. type 'l'
16. type 'o'
17. type 'g'
18. type '('
19. type '0'
20. type ')'
21. type Enter. 
22. cry

**Comment by bluesign** [comment]
```
➜  ~ flow cadence
Welcome to Cadence v0.28.0!
Type '.help' for assistance.

1> log
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1031ae9ec]

goroutine 1 [running]:
github.com/onflow/cadence/runtime.(*REPL).Accept.func1()
	github.com/onflow/cadence@v0.28.0/runtime/repl.go:148 +0xd4
panic({0x10437a440, 0x1051874e0})
```

**Comment by dreamsmasher** [comment]
> ```
> ➜  ~ flow cadence
> Welcome to Cadence v0.28.0!
> Type '.help' for assistance.
> 
> 1> log
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1031ae9ec]
> 
> goroutine 1 [running]:
> github.com/onflow/cadence/runtime.(*REPL).Accept.func1()
> 	github.com/onflow/cadence@v0.28.0/runtime/repl.go:148 +0xd4
> panic({0x10437a440, 0x1051874e0})
> ```

oh no
