### ISSUE TITLE
BUG: Language Server Panic when parsing incomplete dictionary

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#282]
### Problem

Using the latest language server in the vscode extension, I get a panic when typing a dictionary.

### Steps to Reproduce

1. Use this contract
```
pub contract DictionaryPanic {
    pub let panic: {Int:}
}
```
2. See that the language server crashes
```
[Info  - 10:46:55 AM] parsing file:///Users/joshuahannan/flow/onflow/flow-core-contracts/contracts/epochs/test.cdc took 42.932µs
panic: cannot convert unsupported AST type: <nil>

goroutine 38 [running]:
github.com/onflow/cadence/runtime/sema.(*Checker).ConvertType(0xc0004db0e0, 0x0, 0x0, 0x50eeca0, 0x5b14e00)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:862 +0x41a
github.com/onflow/cadence/runtime/sema.(*Checker).convertDictionaryType(0xc0004db0e0, 0xc0002f9310, 0xc000311c00, 0xc0004cd400)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:1075 +0x9b
github.com/onflow/cadence/runtime/sema.(*Checker).ConvertType(0xc0004db0e0, 0x50d93a0, 0xc0002f9310, 0xc0003bb298, 0xc000304890)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:850 +0x287
github.com/onflow/cadence/runtime/sema.(*Checker).ConvertTypeAnnotation(0xc0004db0e0, 0xc0001dffb0, 0x1)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:1258 +0x46
github.com/onflow/cadence/runtime/sema.(*Checker).nonEventMembersAndOrigins(0xc0004db0e0, 0x50ee480, 0xc000344c60, 0xc000300420, 0x1, 0x1, 0x0, 0x0, 0x0, 0x2, ...)
	github.com/onflow/cadence@v0.7.0/runtime/sema/check_composite_declaration.go:1150 +0x4ff
github.com/onflow/cadence/runtime/sema.(*Checker).declareCompositeMembersAndValue.func1(0xc0004db0e0, 0xc000355ee0, 0x2, 0xc000344c60, 0xc0002f5410)
	github.com/onflow/cadence@v0.7.0/runtime/sema/check_composite_declaration.go:573 +0x9e8
github.com/onflow/cadence/runtime/sema.(*Checker).declareCompositeMembersAndValue(0xc0004db0e0, 0xc000355ee0, 0x2)
	github.com/onflow/cadence@v0.7.0/runtime/sema/check_composite_declaration.go:586 +0xce
github.com/onflow/cadence/runtime/sema.(*Checker).VisitProgram(0xc0004db0e0, 0xc0004300d0, 0x25d8f70, 0xe2f759d7f310)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:423 +0x27e
github.com/onflow/cadence/runtime/ast.(*Program).Accept(...)
	github.com/onflow/cadence@v0.7.0/runtime/ast/program.go:54
github.com/onflow/cadence/runtime/sema.(*Checker).Check.func1(...)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:320
github.com/onflow/cadence/runtime/sema.(*Checker).Check(0xc0004db0e0, 0x247438b, 0x5af7e60)
	github.com/onflow/cadence@v0.7.0/runtime/sema/checker.go:325 +0x157
github.com/onflow/cadence/languageserver/server.(*Server).getDiagnostics(0xc0001c0700, 0x50d9260, 0xc0001b6358, 0xc00004a840, 0x54, 0xc000048b00, 0x3a, 0x4ba28e0, 0xc0002c17c0, 0x5, ...)
	github.com/onflow/cadence/languageserver@v0.7.0/server/server.go:1021 +0x3df
github.com/onflow/cadence/languageserver/server.(*Server).DidOpenTextDocument(0xc0001c0700, 0x50d9260, 0xc0001b6358, 0xc0002c17c0, 0xc0002c17c0, 0x0)
	github.com/onflow/cadence/languageserver@v0.7.0/server/server.go:306 +0x9f
github.com/onflow/cadence/languageserver/protocol.(*Server).handleDidOpenTextDocument(0xc0001df7a0, 0xc000310d00, 0xc00035fb90, 0xc0001f36c8, 0x0, 0xc0001f36c0)
	github.com/onflow/cadence/languageserver@v0.7.0/protocol/methods.go:38 +0xcc
github.com/onflow/cadence/languageserver/jsonrpc2.(*handler).Handle(0xc0001b6380, 0x50d8fe0, 0xc0000da008, 0xc0000ec5a0, 0xc0002f92c0)
	@/github.com/onflow/cadence/languageserver/jsonrpc2/server.go:53 +0x2dd
github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0000ec5a0, 0x50d8fe0, 0xc0000da008)
	github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:522 +0x56a
created by github.com/sourcegraph/jsonrpc2.NewConn
	github.com/sourcegraph/jsonrpc2@v0.0.0-20191222043438-96c4efab7ee2/jsonrpc2.go:334 +0x1d9
[Error - 10:46:55 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by turbolent** [comment]
Previously, when there were parse errors, we wouldn't check. To add more advanced features to the language server, like code completion, we need to check programs with parse errors, so now there are parts of the checker which incorrectly assume that the program is syntactically correct. 

Systematically finding all cases where incomplete programs must be handled is going to be quite some work, so we'll have to gradually fix the cases.
