### ISSUE TITLE
Crasher when converting integer to opional address

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3194]
```cadence
var c = true ? Address(0x1) : nil
```

crashes with

```
error: internal error: unreachable
goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/onflow/cadence/runtime/errors.NewUnexpectedError({0x102f0a5fa?, 0x1030fcd68?}, {0x0?, 0x102da56c8?, 0x14000183940?})
	/Users/bastian/Documents/work/cadence/runtime/errors/errors.go:156 +0x3c
github.com/onflow/cadence/runtime/errors.NewUnreachableError(...)
	/Users/bastian/Documents/work/cadence/runtime/errors/errors.go:30
github.com/onflow/cadence/runtime/interpreter.ConvertUnsigned[...]({0x1030f0180?, 0x1400007f320?}, {0x1030fcd68?, 0x1400003b798?}, 0x102d6956c?, 0xffffffffffffffff?, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, 0x140001b1530?}})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:9370 +0x2b0
github.com/onflow/cadence/runtime/interpreter.ConvertUInt64.func1()
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:11043 +0x54
github.com/onflow/cadence/runtime/interpreter.NewUInt64Value({0x1030f0180?, 0x1400007f320?}, 0x140001cb0b0?)
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:10680 +0x60
github.com/onflow/cadence/runtime/interpreter.ConvertUInt64({0x1030f0180?, 0x1400007f320?}, {0x1030fcd68?, 0x1400003b798?}, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, 0x140001b1530?}})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:11040 +0x80
github.com/onflow/cadence/runtime/interpreter.ConvertAddress.func1()
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:21204 +0x40
github.com/onflow/cadence/runtime/interpreter.NewAddressValueFromConstructor({0x1030f0180?, 0x1400007f320?}, 0x140001cb1d0?)
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:21198 +0x64
github.com/onflow/cadence/runtime/interpreter.ConvertAddress({0x1030f0180?, 0x1400007f320?}, {0x1030fcd68?, 0x1400003b798?}, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, 0x140001b1530?}})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/value.go:21214 +0x84
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).convert(0x1400007f320, {0x1030fcd68?, 0x1400003b798?}, {0x103102038, 0x140001b16b0?}, {0x103102038?, 0x140001b16b0?}, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, ...}})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter.go:2050 +0x1684
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).ConvertAndBox(0x0?, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, 0x140001b1530?}}, {0x1030fcd68?, 0x1400003b798?}, {0x103102038?, 0x140001b16b0?}, {0x103102038, ...})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter.go:1823 +0x94
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).transferAndConvert(0x1400007f320?, {0x1030fcd68?, 0x1400003b790?}, {0x103102038, 0x140001b16b0}, {0x103102038, 0x140001b16b0}, {{0x1030f6c00?, 0x10352d670?}, {0x1030f32e8?, ...}})
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter.go:1792 +0xe0
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).visitVariableDeclaration(0x1400007f320, 0x14000144420, 0x0)
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter_statement.go:516 +0x1bc
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitProgram.func1()
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter.go:647 +0x4c
github.com/onflow/cadence/runtime/interpreter.(*Variable).GetValue(...)
	/Users/bastian/Documents/work/cadence/runtime/interpreter/variable.go:30
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitProgram(0x1400007f320, 0x1400015bd40)
	/Users/bastian/Documents/work/cadence/runtime/interpreter/interpreter.go:672 +0x574
github.com/onflow/cadence/runtime.(*REPL).Accept(0x1400010ea80, {0x1400003e840, 0x23, 0x30}, 0x1)
	/Users/bastian/Documents/work/cadence/runtime/repl.go:293 +0x520
github.com/onflow/cadence/runtime/cmd/execute.(*ConsoleREPL).execute(0x140001c20a0, {0x1400021c000?, 0x140001e2601?})
	/Users/bastian/Documents/work/cadence/runtime/cmd/execute/repl.go:150 +0x124
github.com/c-bata/go-prompt.(*Prompt).Run(0x140001e2630)
	/Users/bastian/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.6/prompt.go:84 +0x628
github.com/onflow/cadence/runtime/cmd/execute.(*ConsoleREPL).Run(0x140001c20a0)
	/Users/bastian/Documents/work/cadence/runtime/cmd/execute/repl.go:227 +0x1d8
main.main()
	/Users/bastian/Documents/work/cadence/runtime/cmd/main/main.go:53 +0x1d4
```

**Comment by turbolent** [comment]
git bisect shows that 4a9d6464d6880e61101af1e9e566ce94ce0c0560 broke it
