### ISSUE TITLE
Simple Hello World program panics

### ISSUE THREAD

**Issue by gromgit** [onflow/cadence#361]
### Problem

I'm updating the `cadence` [Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cadence.rb), and it seems to build the CLI (`cadence` a.k.a. `runtime/cmd/main/main`) fine, but the test code panics:
```
$ cat test.cdc
pub fun main(): Int {
  log("Hello, world!")
  return 0
}

$ cadence test.cdc
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ff038]

goroutine 1 [running]:
github.com/onflow/cadence/runtime/interpreter.recoverErrors(0xc000237ec0)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:861 +0x15a
panic(0x12b6200, 0x1566630)
	runtime/panic.go:969 +0x175
github.com/onflow/cadence/runtime/interpreter.HostFunctionValue.Invoke(...)
	github.com/onflow/cadence/runtime/interpreter/function.go:154
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).functionValueInvocationTrampoline(0xc00046a000, 0x137e980, 0xc000184000, 0xc000184650, 0x1, 0x1, 0xc00004ff50, 0x1, 0x1, 0xc00004ff60, ...)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:2101 +0x31a
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitInvocationExpression.func1.1(0x130aa20, 0xc00040ba10, 0xc000182de0, 0x1339a7240137bd00)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:2019 +0x2c8
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x130aa20, 0xc00040ba10, 0x137bd00, 0xc00040ba10)
	github.com/onflow/cadence/runtime/trampoline/trampoline.go:142 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x130aa20, 0xc00040ba10, 0x12a0fe0, 0xc000183280)
	github.com/onflow/cadence/runtime/trampoline/trampoline.go:142 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.Resume.func1(0xc000183260, 0x12a0fe0)
	github.com/onflow/cadence/runtime/trampoline/trampoline.go:154 +0x37
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runUntilNextStatement(0xc00046a000, 0x137bd00, 0xc000183260, 0x0, 0x0, 0xc000182e40)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:605 +0x32
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runAllStatements(0xc00046a000, 0x137bd00, 0xc000182c20, 0x0, 0x0)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:617 +0x53
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).Invoke(0xc00046a000, 0x132075b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/onflow/cadence/runtime/interpreter/interpreter.go:832 +0x114
github.com/onflow/cadence/runtime/cmd/execute.Execute(0xc0000b2030, 0x1, 0x1)
	github.com/onflow/cadence/runtime/cmd/execute/execute.go:41 +0xd0
main.main()
	github.com/onflow/cadence/runtime/cmd/main/main.go:29 +0x56
```

The trouble seems to be the call to `log`. When I comment it out, the test runs fine:
```
$ cat test.cdc
pub fun main(): Int {
//  log("Hello, world!")
  return 0
}

$ cadence test.cdc && echo YES
YES
```

### Steps to Reproduce

See above

### Acceptance Criteria

I need to update the Homebrew formula with a basic "Hello, world!"-style test that should not require network access.

### Context

Updating the Homebrew formula, which would otherwise be stuck at v0.6.0.

**Comment by turbolent** [comment]
@gromgit Thank you for reporting this! 

I noticed this bug while implementing enums, the fix (the https://github.com/onflow/cadence/pull/344/files#diff-040f568b71e2279bc7135a9b78a251b4L123-R123) is in #344, so as soon as that's merged, I'll create a new release. 

BTW, the purpose of the Cadence command line runner and REPL are mainly to help with development of Cadence itself, they're not ready for general-purpose use by Cadence users yet, as I had [mentioned on the initial PR](https://github.com/Homebrew/homebrew-core/pull/57981#issuecomment-660526022). For now they'll miss features and break often.

**Comment by gromgit** [comment]
OK thanks @turbolent , looking forward to the new release. In the meantime, I've removed the `log` call from the formula's test block, so that users can actually use something newer than v0.6.0, even if stuff is missing or broken.

**Comment by turbolent** [comment]
@gromgit Sounds good, thank you for maintaining it! 👏
