### ISSUE TITLE
Running a transaction on testnet returns Execution failed: error: unreachable

### ISSUE THREAD

**Issue by milosponj** [onflow/cadence#703]
### Problem

While trying to run a transaction I adapted from NbaTopShot that basically creates a new Play (it's just called Combination in my contract) I get:

Execution failed:
error: unreachable

The contract can be found here: https://flow-view-source.com/testnet/account/0xbd6caf0b1e6f158f/contract/ChessCombo

The issue is reported on line 131:
 self.id = ChessCombo.nextCombinationId

Interestingly enough, running almost the same transaction for creating a new Compilation (which is a Set in NBA Top Shot) works without issues.

### Steps to Reproduce

1. Run this transaction against testnet:
```import ChessCombo from "../../contracts/ChessCombo.cdc"

transaction(compilationName: String) {
    
    // Local variable for the topshot Admin object
    let adminRef: &ChessCombo.Admin

    prepare(acct: AuthAccount) {

        // borrow a reference to the Admin resource in storage
        self.adminRef = acct.borrow<&ChessCombo.Admin>(from: /storage/ChessComboAdmin)
            ?? panic("Could not borrow a reference to the Admin resource")
    }

    execute {
        
        // Create a set with the specified name
        self.adminRef.createCompilation(name: compilationName)
    }
}
```

2. Get this as response:
```Execution failed:
error: unreachable
goroutine 42258423931 [running]:
runtime/debug.Stack(0xc04667f570, 0xc0462ff4a0, 0x19cd900)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/onflow/cadence/runtime/errors.NewUnreachableError(...)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/errors/errors.go:43
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).getMember(0xc0462ff4a0, 0x19e04e0, 0xc04667f570, 0x19cd900, 0xc1e9abfb00, 0x1827, 0x83, 0x16, 0x1842, 0x83, ...)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/interpreter/interpreter.go:4507 +0xa2
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitMemberExpression.func1(0x162f420, 0xc04667f570, 0xc2350e5be0, 0xc046ad0f78)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/interpreter/interpreter.go:2044 +0x2dc
github.com/onflow/cadence/runtime/trampoline.MapTrampoline.func1(0x162f420, 0xc04667f570, 0xc2350e5880, 0x1339a724019cdb80)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/trampoline/trampoline.go:70 +0x39
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x162f420, 0xc04667f570, 0xc04667f570, 0xc2350e5bc0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/trampoline/trampoline.go:142 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x162f420, 0xc04667f570, 0x13dc1a0, 0xc2350e5be0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/trampoline/trampoline.go:142 +0x42
github.com/onflow/cadence/runtime/trampoline.FlatMap.Resume.func1(0xc2350e5bc0, 0x13dc1a0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/trampoline/trampoline.go:154 +0x37
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runUntilNextStatement(0xc0462ff3b0, 0x19cdb80, 0xc2350e5bc0, 0x0, 0x0, 0xc07cf13890)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/interpreter/interpreter.go:602 +0x35
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runAllStatements(0xc0462ff3b0, 0x19cdb80, 0xc281b2da00, 0x0, 0x0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/interpreter/interpreter.go:643 +0xd0
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeTransaction(0xc0462ff3b0, 0x0, 0xc281b2d980, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/interpreter/interpreter.go:880 +0x137
github.com/onflow/cadence/runtime.(*interpreterRuntime).transactionExecutionFunction.func1(0xc0462ff3b0, 0x0, 0x0, 0x35232047019cda40, 0x60524355)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/runtime.go:475 +0x174
github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret.func1()
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/runtime.go:292 +0xa4
github.com/onflow/cadence/runtime.reportMetric(0xc046ad1388, 0x19edf40, 0xc03e2052c0, 0xc046ad13b0)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/runtime.go:118 +0x93
github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret(0xc00ccc1700, 0xc0466973c0, 0x19edf40, 0xc03e2052c0, 0x19cda40, 0xc039ae6080, 0x0, 0x0, 0x0, 0xc40ae33140, ...)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/runtime.go:286 +0x27f
github.com/onflow/cadence/runtime.(*interpreterRuntime).ExecuteTransaction(0xc00ccc1700, 0xc03831db00, 0x2f1, 0x2f1, 0xc0b6a41e80, 0x1, 0x1, 0x19edf40, 0xc03e2052c0, 0x19cda40, ...)
        /go/pkg/mod/github.com/onflow/cadence@v0.13.7/runtime/runtime.go:416 +0x653
github.com/onflow/flow-go/fvm.(*TransactionInvocator).Process(0xc00b3b4420, 0xc00ccc1710, 0x19dea40, 0x2436300, 0x19a53c0, 0xc00ccc16e0, 0xc2afca6120, 0x19dcbe0, 0xc0000d3820, 0x186a0, ...)
        /app/fvm/transaction.go:114 +0x41c
github.com/onflow/flow-go/fvm.(*TransactionProcedure).Run(0xc046a58c60, 0xc00ccc1710, 0x19dea40, 0x2436300, 0x19a53c0, 0xc00ccc16e0, 0xc2afca6120, 0x19dcbe0, 0xc0000d3820, 0x186a0, ...)
        /app/fvm/transaction.go:56 +0xf4
github.com/onflow/flow-go/fvm.(*VirtualMachine).Run(0xc00ccc1710, 0x19dea40, 0x2436300, 0x19a53c0, 0xc00ccc16e0, 0xc2afca6120, 0x19dcbe0, 0xc0000d3820, 0x186a0, 0x3e80, ...)
        /app/fvm/fvm.go:55 +0x1cf
github.com/onflow/flow-go/engine/execution/computation/computer.(*blockComputer).executeTransaction(0xc0000f58c0, 0xc2c9230300, 0x19e4de0, 0xc04662ae00, 0xc2afca6120, 0xc406f77530, 0xc406f77440, 0x19dea40, 0x2436300, 0x19a53c0, ...)
        /app/engine/execution/computation/computer/computer.go:300 +0x374
github.com/onflow/flow-go/engine/execution/computation/computer.(*blockComputer).executeCollection(0xc0000f58c0, 0x19cb8c0, 0xc28b68dc00, 0xc000000000, 0x19dea40, 0x2436300, 0x19a53c0, 0xc00ccc16e0, 0x0, 0x0, ...)
        /app/engine/execution/computation/computer/computer.go:225 +0x42c
github.com/onflow/flow-go/engine/execution/computation/computer.(*blockComputer).executeBlock(0xc0000f58c0, 0x19cb8c0, 0xc28b68dc00, 0xc0469e4550, 0xc406f77410, 0xc406f77440, 0x0, 0x0, 0x0)
        /app/engine/execution/computation/computer/computer.go:127 +0x5ac
github.com/onflow/flow-go/engine/execution/computation/computer.(*blockComputer).ExecuteBlock(0xc0000f58c0, 0x19cb8c0, 0xc28b68dc00, 0xc0469e4550, 0xc406f77410, 0xc406f77440, 0x0, 0x0, 0x0)
        /app/engine/execution/computation/computer/computer.go:87 +0xaf
github.com/onflow/flow-go/engine/execution/computation.(*Manager).ComputeBlock(0xc00028d880, 0x19cb8c0, 0xc28b68dc00, 0xc0469e4550, 0xc406f77410, 0x0, 0x0, 0x0)
        /app/engine/execution/computation/manager.go:163 +0x259
github.com/onflow/flow-go/engine/execution/ingestion.(*Engine).executeBlock(0xc2604eb380, 0x19cb8c0, 0xc28b68dc00, 0xc0469e4550)
        /app/engine/execution/ingestion/engine.go:526 +0x24e
github.com/onflow/flow-go/engine/execution/ingestion.(*Engine).executeBlockIfComplete.func1()
        /app/engine/execution/ingestion/engine.go:715 +0x48
github.com/onflow/flow-go/engine.(*Unit).Launch.func1(0xc28f245080, 0xc19cedc600)
        /app/engine/unit.go:55 +0x59
created by github.com/onflow/flow-go/engine.(*Unit).Launch
        /app/engine/unit.go:53 +0x99

   --> bd6caf0b1e6f158f.ChessCombo:131:12
```

### Context

I'm trying to learn flow and I'm basically mixing kitty-items and NbaTopShot into my own app. I'm stuck at trying to create what is basically a "Play" struct in NbaTopShot terms.

**Comment by turbolent** [comment]
This happened due to a contract update which added a new field
