### ISSUE TITLE
Field initialization using force assignment results in panic

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/cadence#739]
### Instructions

Deploy the following contract:

```
pub contract ForceAssignNil {

    pub resource Test {}

    pub resource TestResource {

        access(self) var TestHolder: @Test?

        init() {
            self.TestHolder <-! nil
        }

        destroy () {
            destroy self.TestHolder
        }
    }

    init() {
        self.account.save(<- create TestResource(), to: /storage/test)
    }
}
```

### Problem

Force assigning `nil` to `self.TestHolder` throws an `unreachable statement` Go panic, instead of it being a static error.

### Steps to Reproduce

Deploy the ForceAssignNil contract.

See this stack trace
```
    test.go:143: Execution failed:
        error: unreachable
        goroutine 22 [running]:
        runtime/debug.Stack(0xc00060f030, 0xc0003022d0, 0x4ec8180)
        	/usr/local/Cellar/go/1.14/libexec/src/runtime/debug/stack.go:24 +0x9d
        github.com/onflow/cadence/runtime/errors.NewUnreachableError(...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/errors/errors.go:43
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).getMember(0xc0003022d0, 0x4ed3da0, 0xc00060f030, 0x4ec8180, 0xc000240d00, 0x86e, 0x3d, 0xc, 0x883, 0x3d, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:4510 +0xa2
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).memberExpressionGetterSetter.func1.1(0x8, 0x451f6d9)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:1603 +0xbe
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).visitAssignment.func1(0x4b16460, 0xc000681430, 0xc000681430, 0xc000183a60)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:1473 +0x283
        github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x4b16460, 0xc000681430, 0x4a64f40, 0xc000183a80)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/trampoline/trampoline.go:142 +0x42
        github.com/onflow/cadence/runtime/trampoline.FlatMap.Resume.func1(0xc000183a60, 0x4a64f40)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/trampoline/trampoline.go:154 +0x37
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runUntilNextStatement(0xc0003022d0, 0x4ec8400, 0xc000183a60, 0x0, 0x0, 0xc0001f2720)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:602 +0x35
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runAllStatements(0xc0003022d0, 0x4ec8400, 0xc000182240, 0x0, 0x0)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:643 +0xb0
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeFunctionValue(0xc0003022d0, 0x4ed6fa0, 0xc000680ec0, 0xc000240c80, 0x0, 0x0, 0xc00025b2c0, 0x0, 0x0, 0x565a900, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:2180 +0x1a1
        github.com/onflow/cadence/runtime.(*interpreterRuntime).instantiateContract.func1(0xc0003022d0, 0xc000302000, 0x4ed6fa0, 0xc000680ec0, 0x7b4, 0x33, 0xd, 0x7c8, 0x33, 0x21, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:1428 +0x21d
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).declareNonEnumCompositeValue.func5(0x4abd540, 0xc000154b10)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:2654 +0x14b
        github.com/onflow/cadence/runtime/interpreter.(*Variable).GetValue(...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/variable.go:28
        github.com/onflow/cadence/runtime.(*interpreterRuntime).instantiateContract(0xc000248840, 0xc000680940, 0x4ede140, 0xc0007e01e0, 0x4ec8180, 0xc000240d00, 0x0, 0x0, 0x0, 0xc001cb5950, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:1469 +0x6af
        github.com/onflow/cadence/runtime.(*interpreterRuntime).updateAccountContractCode(0xc000248840, 0xc000680940, 0x4ede140, 0xc0007e01e0, 0x4ec8180, 0xc000240d00, 0x0, 0x0, 0x0, 0xc001cb5950, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:1953 +0x4a1
        github.com/onflow/cadence/runtime.(*interpreterRuntime).newAuthAccountContractsChangeFunction.func1(0x0, 0xc000240c80, 0x2, 0x2, 0xc00025b2c0, 0x2, 0x2, 0xc0004c2a10, 0x4ec82c0, 0xc00025ac20, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:1849 +0xee1
        github.com/onflow/cadence/runtime/interpreter.HostFunctionValue.Invoke(...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/function.go:172
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).functionValueInvocationTrampoline(0xc0007d7860, 0x4ed6fa0, 0xc0004c2ab0, 0xc000240b40, 0x2, 0x2, 0xc00025b2c0, 0x2, 0x2, 0xc00025b2e0, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:2216 +0x30e
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitInvocationExpression.func1.1(0x4be79a0, 0xc000634870, 0xc000227700, 0x1339a72404ec8400)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:2134 +0x2c0
        github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x4be79a0, 0xc000634870, 0xc000634870, 0xc000240c40)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/trampoline/trampoline.go:142 +0x42
        github.com/onflow/cadence/runtime/trampoline.FlatMap.FlatMap.func1(0x4be79a0, 0xc000634870, 0x4a64f40, 0xc000240c60)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/trampoline/trampoline.go:142 +0x42
        github.com/onflow/cadence/runtime/trampoline.FlatMap.Resume.func1(0xc000240c40, 0x4a64f40)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/trampoline/trampoline.go:154 +0x37
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runUntilNextStatement(0xc0007d7860, 0x4ec8400, 0xc000240c40, 0x0, 0x0, 0xc000634720)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:602 +0x35
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).runAllStatements(0xc0007d7860, 0x4ec8400, 0xc00025bd40, 0x0, 0x0)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:643 +0xb0
        github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeTransaction(0xc0007d7860, 0x0, 0xc00035c600, 0x3, 0x4, 0x0, 0x0)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/interpreter/interpreter.go:880 +0x118
        github.com/onflow/cadence/runtime.(*interpreterRuntime).transactionExecutionFunction.func1(0xc0007d7860, 0x0, 0x0, 0x174ac4c004ec82c0, 0x60625aa1)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:475 +0x174
        github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret.func1()
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:292 +0xa4
        github.com/onflow/cadence/runtime.reportMetric(0xc0004bdcf8, 0x4ede140, 0xc0007e01e0, 0xc0004bdd20)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:118 +0x93
        github.com/onflow/cadence/runtime.(*interpreterRuntime).interpret(0xc000248840, 0xc0004c2a80, 0x4ede140, 0xc0007e01e0, 0x4ec82c0, 0xc00025ac20, 0x0, 0x0, 0x0, 0xc001cb5950, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:286 +0x27f
        github.com/onflow/cadence/runtime.(*interpreterRuntime).ExecuteTransaction(0xc000248840, 0xc0002b9e00, 0xa9, 0x200, 0xc000600450, 0x2, 0x2, 0x4ede140, 0xc0007e01e0, 0x4ec82c0, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/cadence@v0.13.10/runtime/runtime.go:416 +0x63e
        github.com/onflow/flow-go/fvm.(*TransactionInvocator).Process(0xc000190c60, 0xc000248850, 0x4ed3020, 0x5616410, 0x4eafe80, 0xc000248830, 0x0, 0x0, 0x0, 0x186a0, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-go@v0.14.9/fvm/transaction.go:114 +0x432
        github.com/onflow/flow-go/fvm.(*TransactionProcedure).Run(0xc0002ac000, 0xc000248850, 0x4ed3020, 0x5616410, 0x4eafe80, 0xc000248830, 0x0, 0x0, 0x0, 0x186a0, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-go@v0.14.9/fvm/transaction.go:56 +0xf4
        github.com/onflow/flow-go/fvm.(*VirtualMachine).Run(0xc000248850, 0x4ed3020, 0x5616410, 0x4eafe80, 0xc000248830, 0x0, 0x0, 0x0, 0x186a0, 0x3e80, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-go@v0.14.9/fvm/fvm.go:55 +0x1be
        github.com/onflow/flow-emulator.(*Blockchain).executeNextTransaction.func1(0xc0002793e0, 0xc000000001, 0xc0004d49c0, 0xc000667448, 0x6a06855d615ab652, 0xd282ff9daf9846ea)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-emulator@v0.16.2/blockchain.go:810 +0x251
        github.com/onflow/flow-emulator.(*pendingBlock).ExecuteNextTransaction(0xc000229e60, 0xc0004bf190, 0x7, 0x0, 0x0)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-emulator@v0.16.2/pendingBlock.go:151 +0x12b
        github.com/onflow/flow-emulator.(*Blockchain).executeNextTransaction(0xc0005fa9c0, 0x4ed3020, 0x5616410, 0x4eafe80, 0xc000248830, 0x0, 0x0, 0x0, 0x186a0, 0x3e80, ...)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-emulator@v0.16.2/blockchain.go:800 +0x7d
        github.com/onflow/flow-emulator.(*Blockchain).ExecuteNextTransaction(0xc0005fa9c0, 0x0, 0x0, 0x0)
        	/Users/joshuahannan/go/pkg/mod/github.com/onflow/flow-emulator@v0.16.2/blockchain.go:786 +0x23f
        github.com/onflow/lib/go/flow-core-contracts.Submit(0xc00019a6c0, 0xc0005fa9c0, 0xc0004d4a80, 0x0)
        	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/test.go:135 +0xe1
        github.com/onflow/lib/go/flow-core-contracts.signAndSubmit(0xc00019a6c0, 0xc0005fa9c0, 0xc0004d4a80, 0xc0004bfb80, 0x2, 0x2, 0xc0004bfbe0, 0x2, 0x2, 0x0)
        	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/test.go:120 +0x1a9
        github.com/onflow/lib/go/flow-core-contracts.deployCollectionContract(0xc00019a6c0, 0xc0005fa9c0, 0x5054712f2f0ecf01, 0x315e75b61c6b9b17, 0xee5e8fa7c1d2fcf3, 0x4eb1960, 0xc002a94c60, 0xc0007a5f00)
        	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/lockedtokens_helpers.go:141 +0x596
        github.com/onflow/lib/go/flow-core-contracts.deployAllCollectionContracts(0xc00019a6c0, 0xc0005fa9c0, 0xc00068b8b0, 0xc0007a5f00, 0x0, 0x4c1a45f)
        	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/lockedtokens_helpers.go:185 +0x42c
        github.com/onflow/lib/go/flow-core-contracts.TestStakingCollectionDeploy(0xc00019a6c0)
        	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/flow_stakingcollection_test.go:14 +0x92
        testing.tRunner(0xc00019a6c0, 0x4d89360)
        	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc
        created by testing.(*T).Run
        	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357
        
          --> f3fcd2c1a78f5eee.FlowStakingCollection:61:12
```

### Acceptance Criteria

TBD

### Context

Discovered during StakingCollection work.

**Comment by turbolent** [comment]
@JeffreyDoyle Thank you for opening this bug report! 

It looks like this particular case of force-assigning in the initializer isn't handled properly: the force-assignment gets the current value, but the assignment is the first assignment, so there not being a value for the field is actually not an implementation error, but normal in this particular case (initialization).
