### ISSUE TITLE
Fatal Error when parsing a Cadence array in Go

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#928]
### Problem

Using:
```
emulator 0.19.0
go-sdk 0.19.0
cadence 0.15.1
```

When parsing an array that I returned from a script, I get the error described in the stack trace below. 👇 

### Steps to Reproduce

1. Check out the `machine-account` branch in the flow-core-contracts repo
2. `cd lib/go/test`
3. `go test -run TestStakingCollectionGetTokens`
4. Observe the error

This happens when using [this script](https://github.com/onflow/flow-core-contracts/blob/machine-account/transactions/stakingCollection/scripts/get_node_ids.cdc) to call [this function. ](https://github.com/onflow/flow-core-contracts/blob/machine-account/contracts/FlowStakingCollection.cdc#L845). 
The error happens on the line when [we try to get the values from the Cadence array.](https://github.com/onflow/flow-core-contracts/blob/machine-account/lib/go/test/lockedtokens_helpers.go#L438)

One thing that makes this strange is that in a different branch, we do the exact same thing and it works.
Context: The [`josh/proxycollection`](https://github.com/onflow/flow-core-contracts/tree/josh/proxycollection) branch has the basic staking collection contract, where the tests are all passing. See [this PR for more information](https://github.com/onflow/flow-core-contracts/pull/119) about what the staking collection does.
I encountered this error when trying to integrate the staking collection contract with the epoch contracts [in this branch.](https://github.com/onflow/flow-core-contracts/pull/63)
I made changes to the staking collection contract and some of its transactions and scripts, but I did not change anything about this specific script or test, so it seems like it should still be working fine.

**Stack Trace:**

```
runtime: unexpected return pc for github.com/onflow/flow-emulator.(*Blockchain).ExecuteScriptAtBlock called from 0xc0012a1818
stack: frame={sp:0xc0012a1110, fp:0xc0012a1790} stack=[0xc00129a000,0xc0012a2000)
000000c0012a1010:  0000000000000000  000000c0012a1060 
000000c0012a1020:  00000000040194de <runtime.(*mcentral).cacheSpan+414>  000000000e53c8a8 
000000c0012a1030:  0000000000000000  000000c0012a1060 
000000c0012a1040:  0000006a040d78f1  0000000000002000 
000000c0012a1050:  000000000e53c8a8  000000c000442dd0 
000000c0012a1060:  000000c0012a1080  0000000000000019 
000000c0012a1070:  000000000576ca58  000000000e53c8a8 
000000c0012a1080:  000000c0012a10b8  000000000400dd04 <runtime.(*mcache).nextFree+164> 
000000c0012a1090:  000000000e53c8a8  000000000400e1a6 <runtime.mallocgc+790> 
000000c0012a10a0:  000000c00084a300  0000000000000040 
000000c0012a10b0:  000000000e53c8a8  000000c0012a1158 
000000c0012a10c0:  000000000400e1a6 <runtime.mallocgc+790>  0100000005a88560 
000000c0012a10d0:  0000000000000000  0000000000000032 
000000c0012a10e0:  000000c00084a300  0000000004051801 <runtime.intstring+273> 
000000c0012a10f0:  0101000000000010  000000c00005e800 
000000c0012a1100:  0000000005a88560  000000000400e1a6 <runtime.mallocgc+790> 
000000c0012a1110: <000000c0012a1150  000000000405122f <runtime.rawstringtmp+111> 
000000c0012a1120:  000000c00005e800  0000000005a88560 
000000c0012a1130:  000000c0012a1160  010000000404d06c 
000000c0012a1140:  0000000000000000  0000000000000008 
000000c0012a1150:  000000c0002e0a00  000000c00084a300 
000000c0012a1160:  000000c0012a1198  0000000004054aa1 <runtime.step+273> 
000000c0012a1170:  000000000566dba0  0000000000057307 
000000c0012a1180:  0000000000057307  0000008100000002 
000000c0012a1190:  0000000000057307  000000c0012a1240 
000000c0012a11a0:  0000000004053ce5 <runtime.pcvalue+341>  000000000566dba0 
000000c0012a11b0:  0000000000057307  0000000000057308 
000000c0012a11c0:  000000c0012a1200  000000c0012a11fc 
000000c0012a11d0:  000000000566ad00  000000000566dba2 
000000c0012a11e0:  0000000000057305  0000000000057305 
000000c0012a11f0:  00000000040520a7 <runtime.findnull+135>  00000000056a9320 
000000c0012a1200:  0000000000000ce0  000000000005a100 
000000c0012a1210:  000000000400ee82 <runtime.persistentalloc+130>  000000c0012a1228 
000000c0012a1220:  000000000e5a68b0  00000000040624f0 <runtime.persistentalloc.func1+0> 
000000c0012a1230:  0000000000000100  0000000000000000 
000000c0012a1240:  0000000005771e10  000000c0012a1220 
000000c0012a1250:  000000c0012a1288  000000000402d60e <runtime.newBucket+94> 
000000c0012a1260:  0000000000000100  0000000000000000 
000000c0012a1270:  0000000005771e10  000000000e5a68b0 
000000c0012a1280:  0000000000000100  000000c0012a12e8 
000000c0012a1290:  000000000402d9ef <runtime.stkbucket+655>  000000000e5a68e0 
000000c0012a12a0:  000000c0012a1340  0000000000000050 
000000c0012a12b0:  000000c0012a12f8  000000c0001e6180 
000000c0012a12c0:  0000000000000004  000000c0012a1340 
000000c0012a12d0:  c2e3334f97b25ab1  0000000000020c10 
000000c0012a12e0:  000000000e5a68b0  000000c0012a1460 
000000c0012a12f0:  000000000402df63 <runtime.mProf_Malloc+419>  000000c0012a1448 
000000c0012a1300:  000000000e5a6930  000000c0012a1340 
000000c0012a1310:  000000000000000a  0000000000000020 
000000c0012a1320:  00000000040d5c01 <fmt.(*fmt).fmtInteger+449>  000000000e5a68b0 
000000c0012a1330:  0000003500442e79  000000000000000a 
000000c0012a1340:  00000000041038bc <testing.(*common).decorate+1340>  00000000041036d9 <testing.(*common).decorate+857> 
000000c0012a1350:  00000000041047fa <testing.(*common).logDepth+634>  0000000004104aca <testing.(*common).Log+106> 
000000c0012a1360:  0000000004104a7e <testing.(*common).Log+30>  00000000048f4295 <github.com/onflow/lib/go/flow-core-contracts.executeScriptAndCheck+485> 
000000c0012a1370:  00000000048ed552 <github.com/onflow/lib/go/flow-core-contracts.verifyStakingCollectionInfo+2386>  000000000498f20d <github.com/onflow/lib/go/flow-core-contracts.TestStakingCollectionGetTokens.func1+973> 
000000c0012a1380:  0000000004105a6c <testing.tRunner+220>  0000000004067961 <runtime.goexit+1> 
000000c0012a1390:  0000000000000000  0000000000000000 
000000c0012a13a0:  0000000000000000  0000000000000000 
000000c0012a13b0:  0000000000000000  0000000000000000 
000000c0012a13c0:  0000000000000000  0000000000000000 
000000c0012a13d0:  0000000000000000  0000000000000000 
000000c0012a13e0:  0000000000000000  0000000000000000 
000000c0012a13f0:  0000000000000000  0000000000000000 
000000c0012a1400:  0000000000000000  0000000000000000 
000000c0012a1410:  0000000000000000  0000000000000000 
000000c0012a1420:  0000000000000000  0000000000000000 
000000c0012a1430:  0000000000000000  0000000000000000 
000000c0012a1440:  000000000e5a68b0  0000000004063a10 <runtime.mProf_Malloc.func1+0> 
000000c0012a1450:  000000c000700000  000000000e5a68b0 
000000c0012a1460:  000000c0012a1480  000000000400ec79 <runtime.profilealloc+89> 
000000c0012a1470:  000000c000700000  0000000000000280 
000000c0012a1480:  000000c0012a1520  000000000400e301 <runtime.mallocgc+1137> 
000000c0012a1490:  000000c00005e800  000000c000700000 
000000c0012a14a0:  0000000000000280  000000000e324c10 
000000c0012a14b0:  000000c0005ff701  01010000040eeec7 
000000c0012a14c0:  0000000000000000  0000000000000280 
000000c0012a14d0:  000000c000700000  0000000000000000 
000000c0012a14e0:  000000c00005e800  000000c00005e800 
000000c0012a14f0:  0000000005a88560  0000000000000000 
000000c0012a1500:  000000c0012a1530  000000000404d06c <runtime.makeslice+108> 
000000c0012a1510:  0000000000000080  0000000004b0bce0 
000000c0012a1520:  000000c0012a1588  000000000404d29e <runtime.growslice+414> 
000000c0012a1530:  000000c000700000  000000c0001e08c0 
000000c0012a1540:  000000000000012f  000000c000700000 
000000c0012a1550:  0000000000000176  0000000000000280 
000000c0012a1560:  000000000000012f  0000000000000280 
000000c0012a1570:  0000000000000007  000000c000700000 
000000c0012a1580:  000000c000700000  000000c0012a16e8 
000000c0012a1590:  0000000004103737 <testing.(*common).decorate+951>  000000c00070017f 
000000c0012a15a0:  000000c0001e08be  0000000000000000 
000000c0012a15b0:  0000000000000140  0000000000000176 
000000c0012a15c0:  000000c000700000  000000000000012f 
000000c0012a15d0:  0000000000000280  0000000000000008 
000000c0012a15e0:  0000000000000000  000000000566dad0 
000000c0012a15f0:  00000000056dd000  0000000000000000 
000000c0012a1600:  0000000000000007  00000000000000b0 
000000c0012a1610:  0000000000000006  0000000000000007 
000000c0012a1620:  0000000000000280  000000000000017f 
000000c0012a1630:  000000c0001e08be  00000000056a9360 
000000c0012a1640:  000000c0006f0f00  000000c000700000 
000000c0012a1650:  000000c0005ff760  000000c001bb6110 
000000c0012a1660:  000000c0006f0f08  000000c0012a1700 
000000c0012a1670:  00000000040dbb23 <fmt.(*pp).printArg+2115>  0000000004b0bce0 
000000c0012a1680:  000000c001bb6110  0000000004b0b220 
000000c0012a1690:  000000c0002e0a10  000000c0012a16e8 
000000c0012a16a0:  0000000004034874 <runtime.deferreturn+180>  0000000004e401b8 
000000c0012a16b0:  000000c0012a16f8  00000000056a9320 
000000c0012a16c0:  000000c0001e6180  0000000004e401b8 
000000c0012a16d0:  000000c0001e61a8  00000000012a1758 
000000c0012a16e0:  000000c0012a16f8  000000c0012a17c8 
000000c0012a16f0:  000000000410487f <testing.(*common).logDepth+767>  000000c001c45440 
000000c0012a1700:  000000c000700000  0000000000000180 
000000c0012a1710:  0000000000000004  000000c000700000 
000000c0012a1720:  0000000000000180  0000000004073dec <sync.(*Pool).Put+92> 
000000c0012a1730:  000000000572d220  000000c000601180 
000000c0012a1740:  0000000000000003  0000000000001000 
000000c0012a1750:  0000000000000de8  0000000000000008 
000000c0012a1760:  000000c0012a16f8  00000000041045f4 <testing.(*common).logDepth+116> 
000000c0012a1770:  0000000000000000  0000000000000000 
000000c0012a1780:  0000000000000008 !000000c0012a1818 
000000c0012a1790: >0000000004035117 <runtime.runOpenDeferFrame+183>  0000000004e420cd 
000000c0012a17a0:  000000c000000000  0000000004e420ce 
000000c0012a17b0:  0000000000203000  0000000000203000 
000000c0012a17c0:  0000000000000001  0000000800000000 
000000c0012a17d0:  0000000000000000  000000c001c45440 
000000c0012a17e0:  0000000004034f6b <runtime.addOneOpenDeferFrame+123>  000000c0012a17f0 
000000c0012a17f0:  0000000004064520 <runtime.addOneOpenDeferFrame.func1+0>  00000000048a0246 <github.com/onflow/flow-emulator.(*Blockchain).ExecuteScriptAtBlock+998> 
000000c0012a1800:  000000c0012a1110  000000c0001e6180 
000000c0012a1810:  000000c000384460  000000c0012a18c0 
000000c0012a1820:  0000000004035836 <runtime.gopanic+822>  000000c0001e6180 
000000c0012a1830:  0000000000000000  0000000000000000 
000000c0012a1840:  000000c0005fbcb0  010000c000197810 
000000c0012a1850:  0000000000000000  000000c00005e800 
000000c0012a1860:  0000000005a88560  000000c0001e6180 
000000c0012a1870:  000000c001bb6100  000000c000384460 
000000c0012a1880:  000000c0001e61a8  0000000000000000 
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x4cc29a5, 0x11)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72
runtime.gentraceback(0x48a0246, 0xc0012a1110, 0x0, 0xc0001e6180, 0x0, 0x0, 0x7fffffff, 0x700002482f18, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/traceback.go:273 +0x19fb
runtime.addOneOpenDeferFrame.func1()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:719 +0x91
runtime.systemstack(0x5b00000)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:1041

goroutine 555 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:330 fp=0xc0012a17e8 sp=0xc0012a17e0 pc=0x4065870
runtime.addOneOpenDeferFrame(0xc0001e6180, 0x0, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:718 +0x7b fp=0xc0012a1828 sp=0xc0012a17e8 pc=0x4034f6b
panic(0x4b721a0, 0xc0005fbcb0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:969 +0x336 fp=0xc0012a18d0 sp=0xc0012a1828 pc=0x4035836
runtime.panicdottypeE(...)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/iface.go:260
runtime.panicdottypeI(0x0, 0x4c250a0, 0x4b959c0)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/iface.go:270 +0xcb fp=0xc0012a18f8 sp=0xc0012a18d0 pc=0x400ba4b
github.com/onflow/lib/go/flow-core-contracts.verifyStakingCollectionInfo(0xc001c45440, 0xc000722540, 0x0, 0x0, 0x4cc1484, 0x10, 0x4cc0d24, 0x10, 0xc001b3b860, 0x10, ...)
	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/lockedtokens_helpers.go:438 +0x1468 fp=0xc0012a1b30 sp=0xc0012a18f8 pc=0x48ee068
github.com/onflow/lib/go/flow-core-contracts.TestStakingCollectionGetTokens.func1(0xc001c45440)
	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/flow_stakingcollection_test.go:70 +0x3cd fp=0xc0012a1f80 sp=0xc0012a1b30 pc=0x498f20d
testing.tRunner(0xc001c45440, 0xc00144ea80)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc fp=0xc0012a1fd0 sp=0xc0012a1f80 pc=0x4105a6c
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0012a1fd8 sp=0xc0012a1fd0 pc=0x4067961
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357

goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000208120)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:957 +0x238
testing.tRunner(0xc000208120, 0xc0000dbe10)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:996 +0x10b
testing.runTests(0xc0001bc7c0, 0x5737340, 0x20, 0x20, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1283 +0x2a7
testing.(*M).Run(0xc000202580, 0x0)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1200 +0x15f
main.main()
	_testmain.go:106 +0x135

goroutine 50 [chan receive]:
testing.(*T).Run(0xc001c45440, 0x4ce83a3, 0x3c, 0xc00144ea80, 0xc)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1044 +0x37e
github.com/onflow/lib/go/flow-core-contracts.TestStakingCollectionGetTokens(0xc000208240)
	/Users/joshuahannan/flow/onflow/flow-core-contracts/lib/go/test/flow_stakingcollection_test.go:59 +0x2f2
testing.tRunner(0xc000208240, 0x4e3e098)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357

goroutine 51 [chan receive]:
testing.runTests.func1.1(0xc000208120)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1290 +0x3b
created by testing.runTests.func1
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1290 +0xac
exit status 2
```

**Comment by turbolent** [comment]
@joshuahannan Thank you for the report! The stack trace looks quite strange. What Go version are you using?

**Comment by joshuahannan** [comment]
I am using `go version go1.14 darwin/amd64`

**Comment by joshuahannan** [comment]
Updating my go version fixed this issue, so I think I can close this. 👍
